#!/bin/sh

if [ -f /System/Library/Extensions/Asepsis.kext/Contents/Resources/asepsisctl ]; then
	# uninstall previous wrapper
	# note this command may not be available prior Asepsis 1.2 (it will fail silently)
	/System/Library/Extensions/Asepsis.kext/Contents/Resources/asepsisctl uninstall_wrapper

	# use explicit code to for Asepsis 1.1 compatibility
	# TODO: in the future drop Asepsis 1.1 compatibility and use asepsisctl uninstall
	killall -USR1 asepsisd
	sleep 2
	launchctl unload "/Library/LaunchDaemons/com.binaryage.asepsis.daemon.plist" 
	kextunload "/System/Library/Extensions/Asepsis.kext"
fi

exit 0